preStartParams= function()
{
  $g.params([{"name":"transport_velocity","type":"double","value":400,"unit":"mm/s"},{"name":"deposition_velocity","type":"double","value":200,"unit":"mm/s"},{"name":"return_velocity","type":"double","value":600,"unit":"mm/s"},{"name":"supply_factor","type":"double","value":3,"unit":"[]"},{"name":"layer_thickness","type":"double","value":0.03,"unit":"mm"},{"name":"platform_offset","type":"double","value":0.5,"unit":"mm"}])
  $p[1].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[2].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[3].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[4].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[5].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[6].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[7].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[8].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[9].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[10].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[11].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
  $p[12].params([{"name":"sky_writing_enabled","type":"bool","unit":"","value":false},{"name":"enable_pulsed_mode","type":"bool","value":false},{"name":"sky_writing_limit","type":"doubleInterval","unit":"rad","value":{"min":0,"max":3.1416,"value":0}},{"name":"mark_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"laser_power","type":"double","unit":"W","value":0},{"name":"laser_on_delay","type":"double","unit":"&mu;s","value":50},{"name":"polygon_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":400}},{"name":"jump_delay","type":"doubleInterval","unit":"&mu;s","value":{"min":0,"max":2000000000,"value":300}},{"name":"defocus","type":"double","unit":"mm","value":0},{"name":"jump_speed","type":"doubleInterval","unit":"mm/    s","value":{"min":1,"max":5000,"value":3000}},{"name":"laser_modulation_frequency","type":"double","unit":"MHz","value":1},{"name":"laser_modulation_width","type":"double","unit":"&mu;s","value":10000},{"name":"laser_off_delay","type":"double","unit":"&mu;s","value":50}])
}


preStartSelection= function()
{
  $p.use(1,2,3,4,5,6,7,8,9,10,11,12)
  $p.select(1,167)
}

preStartParams()
preStartSelection()

// This is executed thereafter
layer= function()
{
  $p[1].params([{"name":"mark_speed","type":"doubleInterval","unit":"mm/s","value":{"min":1,"max":5000,"value":3000}}])
  for(p:$p)
  {
    $m.record_sensor($s[2Pyrometer],p)
    $m.expose(p[next;$h],$c[scanner_1])
    $m.stop_record_sensor($s[2Pyrometer])
  }
  $m.add_layer($g)
}

repeat(layer)
